variables:
    GIT_SUBMODULE_STRATEGY: "recursive"

before_script:
    - git lfs fetch
    - git lfs checkout

after_script:
    - echo log-after_script

stages:
    - check
    - package
    - deploy

check:
    stage: check
    script:
        - echo check
        #- 'cppcheck . --enable=warning,style,performance,portability --xml-version=2 --error-exitcode=1 -i external/ -i build/ -i libdraco_ue4/'
    tags:
        - cppcheck

package_windows_ue4.10:
    stage: package
    script:
        - 'if exist libdraco_ue4 rmdir /s /q libdraco_ue4'
        #- 'echo build start'
        - 'call "%VS140COMNTOOLS%VsDevCmd.bat"'
        - 'cd external/draco'
        - 'if exist build32vs2015 rmdir /s /q build32vs2015'
        - 'if exist build64vs2015 rmdir /s /q build64vs2015'
        - 'mkdir build32vs2015'
        - 'cd build32vs2015'
        - 'cmake -G "Visual Studio 14 2015" ../'
        - 'msbuild dracodec.vcxproj /t:Build /p:Configuration="Release" /p:Platform="Win32"'
        - 'msbuild dracoenc.vcxproj /t:Build /p:Configuration="Release" /p:Platform="Win32"'
        - 'cd ../'
        - 'mkdir build64vs2015'
        - 'cd build64vs2015'
        - 'cmake -G "Visual Studio 14 2015 Win64" ../'
        - 'msbuild dracodec.vcxproj /t:Build /p:Configuration="Release" /p:Platform="x64"'
        - 'msbuild dracoenc.vcxproj /t:Build /p:Configuration="Release" /p:Platform="x64"'
        - 'cd ../'
        - 'cd ../../'
        #- 'echo build end'
        - 'xcopy README.md libdraco_ue4\README.md* /r /y'
        - 'xcopy LICENSE.md libdraco_ue4\LICENSE.md* /r /y'
        - 'xcopy libdraco_ue4.10.Build.cs libdraco_ue4\libdraco_ue4.Build.cs* /r /y'
        - 'xcopy external\draco\src\draco\core\*.h libdraco_ue4\libdraco-1.2.5\include\draco\core\ /s/r/y'
        - 'xcopy external\draco\src\draco\metadata\*.h libdraco_ue4\libdraco-1.2.5\include\draco\metadata\ /s /r /y'
        - 'xcopy external\draco\src\draco\mesh\*.h libdraco_ue4\libdraco-1.2.5\include\draco\mesh\ /s /r /y'
        - 'xcopy external\draco\src\draco\point_cloud\*.h libdraco_ue4\libdraco-1.2.5\include\draco\point_cloud\ /s /r /y'
        - 'xcopy external\draco\src\draco\attributes\*.h libdraco_ue4\libdraco-1.2.5\include\draco\attributes\ /s /r /y'
        - 'xcopy external\draco\src\draco\compression\*.h libdraco_ue4\libdraco-1.2.5\include\draco\compression\ /s /r /y'
        - 'xcopy external\draco\src\draco\io\*.h libdraco_ue4\libdraco-1.2.5\include\draco\io\ /s /r /y'
        - 'xcopy external\draco\build32vs2015\Release\*.lib libdraco_ue4\libdraco-1.2.5\lib\vs2015\win32\Release\ /s /r /y'
        - 'xcopy external\draco\build64vs2015\Release\*.lib libdraco_ue4\libdraco-1.2.5\lib\vs2015\win64\Release\ /s /r /y'
    artifacts:
        name: "libdrack_ue4.win32.%CI_PIPELINE_ID%.%CI_JOB_ID%"
        expire_in: 1 week
        paths:
            - libdraco_ue4/*
    tags:
        - win32
        - win64
        - cmake
        - vs2015

package_windows_ue4.16:
    stage: package
    script:
        - 'if exist libdraco_ue4 rmdir /s /q libdraco_ue4'
        #- 'echo build start'
        - 'call "%VS140COMNTOOLS%VsDevCmd.bat"'
        - 'cd external/draco'
        - 'if exist build32vs2015 rmdir /s /q build32vs2015'
        - 'if exist build64vs2015 rmdir /s /q build64vs2015'
        - 'mkdir build32vs2015'
        - 'cd build32vs2015'
        - 'cmake -G "Visual Studio 14 2015" ../'
        - 'msbuild dracodec.vcxproj /t:Build /p:Configuration="Release" /p:Platform="Win32"'
        - 'msbuild dracoenc.vcxproj /t:Build /p:Configuration="Release" /p:Platform="Win32"'
        - 'cd ../'
        - 'mkdir build64vs2015'
        - 'cd build64vs2015'
        - 'cmake -G "Visual Studio 14 2015 Win64" ../'
        - 'msbuild dracodec.vcxproj /t:Build /p:Configuration="Release" /p:Platform="x64"'
        - 'msbuild dracoenc.vcxproj /t:Build /p:Configuration="Release" /p:Platform="x64"'
        - 'cd ../'
        - 'cd ../../'
        #- 'echo build end'
        - 'xcopy README.md libdraco_ue4\README.md* /r /y'
        - 'xcopy LICENSE.md libdraco_ue4\LICENSE.md* /r /y'
        - 'xcopy libdraco_ue4.16.Build.cs libdraco_ue4\libdraco_ue4.Build.cs* /r /y'
        - 'xcopy external\draco\src\draco\core\*.h libdraco_ue4\libdraco-1.2.5\include\draco\core\ /s/r/y'
        - 'xcopy external\draco\src\draco\metadata\*.h libdraco_ue4\libdraco-1.2.5\include\draco\metadata\ /s /r /y'
        - 'xcopy external\draco\src\draco\mesh\*.h libdraco_ue4\libdraco-1.2.5\include\draco\mesh\ /s /r /y'
        - 'xcopy external\draco\src\draco\point_cloud\*.h libdraco_ue4\libdraco-1.2.5\include\draco\point_cloud\ /s /r /y'
        - 'xcopy external\draco\src\draco\attributes\*.h libdraco_ue4\libdraco-1.2.5\include\draco\attributes\ /s /r /y'
        - 'xcopy external\draco\src\draco\compression\*.h libdraco_ue4\libdraco-1.2.5\include\draco\compression\ /s /r /y'
        - 'xcopy external\draco\src\draco\io\*.h libdraco_ue4\libdraco-1.2.5\include\draco\io\ /s /r /y'
        - 'xcopy external\draco\build32vs2015\Release\*.lib libdraco_ue4\libdraco-1.2.5\lib\vs2015\win32\Release\ /s /r /y'
        - 'xcopy external\draco\build64vs2015\Release\*.lib libdraco_ue4\libdraco-1.2.5\lib\vs2015\win64\Release\ /s /r /y'
    artifacts:
        name: "libdrack_ue4.win32.%CI_PIPELINE_ID%.%CI_JOB_ID%"
        expire_in: 1 week
        paths:
            - libdraco_ue4/*
    tags:
        - win32
        - win64
        - cmake
        - vs2015

libdraco_ue4.10:
    stage: deploy
    script:
        - 'butler login'
        - 'butler push ./libdraco_ue4 c4gio/libdraco-ue4:ue4.10'
        - 'butler logout'
    artifacts:
        name: "$CI_JOB_NAME.$CI_PIPELINE_ID"
        expire_in: 1 week
        paths:
            - $CI_JOB_NAME/*
    when: manual
    dependencies:
        - package_windows_ue4.10
    tags:
        - linux
        - python
        - itchio
        - butler

libdraco_ue4.16:
    stage: deploy
    script:
        - 'butler login'
        - 'butler push ./libdraco_ue4 c4gio/libdraco-ue4:ue4.16'
        - 'butler logout'
    artifacts:
        name: "$CI_JOB_NAME.$CI_PIPELINE_ID"
        expire_in: 1 week
        paths:
            - $CI_JOB_NAME/*
    when: manual
    dependencies:
        - package_windows_ue4.16
    tags:
        - linux
        - python
        - itchio
        - butler
