variables:
    GIT_SUBMODULE_STRATEGY: "recursive"

before_script:
    - git lfs fetch
    - git lfs checkout

after_script:
    - echo log-after_script

stages:
    - check
    - build
    - package
    - deploy

check:
    stage: check
    script:
        - echo check
        #- 'cppcheck . --enable=warning,style,performance,portability --xml-version=2 --error-exitcode=1 -i external/ -i build/ -i libdraco_ue4/'
    tags:
        - cppcheck

compile_draco.windows:
    stage: build
    script:
        - 'if exist output rmdir /s /q output'
        - 'call "%VS140COMNTOOLS%VsDevCmd.bat"'
        - 'cd external/draco'
        - 'if exist build32vs2015 rmdir /s /q build32vs2015'
        - 'if exist build64vs2015 rmdir /s /q build64vs2015'
        - 'mkdir build32vs2015'
        - 'cd build32vs2015'
        - 'cmake -G "Visual Studio 14 2015" ../'
        - 'msbuild dracodec.vcxproj /t:Build /p:Configuration="Release" /p:Platform="Win32"'
        - 'msbuild dracoenc.vcxproj /t:Build /p:Configuration="Release" /p:Platform="Win32"'
        - 'cd ../'
        - 'mkdir build64vs2015'
        - 'cd build64vs2015'
        - 'cmake -G "Visual Studio 14 2015 Win64" ../'
        - 'msbuild dracodec.vcxproj /t:Build /p:Configuration="Release" /p:Platform="x64"'
        - 'msbuild dracoenc.vcxproj /t:Build /p:Configuration="Release" /p:Platform="x64"'
        - 'cd ../'
        - 'cd ../../'
        - 'xcopy external\draco\build32vs2015\Release\*.lib output\lib\win32\vs2015\ /s /r /y'
        - 'xcopy external\draco\build64vs2015\Release\*.lib output\lib\win64\vs2015\ /s /r /y'
    artifacts:
        name: "libdraco.windows.%CI_PIPELINE_ID%.%CI_JOB_ID%"
        expire_in: 1 week
        paths:
            - output\lib\*
    tags:
        - win32
        - win64
        - cmake
        - vs2015

compile_draco.linux:
    stage: build
    script:
        - 'rm -rf output'
        - 'cd external/draco'
        - 'rm -rf build'
        - 'mkdir build'
        - 'cd build'
        - 'cmake -G "Unix Makefiles" ../'
        - 'make dracodec'
        - 'make dracoenc'
        - 'cd ../../../'
        - 'mkdir -p output/lib/linux'
        - 'cp external/draco/build/libdra*.a output/lib/linux/'
    artifacts:
        name: "libdraco.linux.%CI_PIPELINE_ID%.%CI_JOB_ID%"
        expire_in: 1 week
        paths:
            - output/lib/*
    tags:
        - linux
        - gcc
        - cmake
        - make

compile_draco.macos:
    stage: build
    script:
        - 'rm -rf output'
        - 'cd external/draco'
        - 'rm -rf build'
        - 'mkdir build'
        - 'cd build'
        - 'cmake -G "Unix Makefiles" ../'
        - 'make dracodec'
        - 'make dracoenc'
        - 'cd ../../../'
        - 'mkdir -p output/lib/macos'
        - 'cp external/draco/build/libdraco*.a output/lib/macos/'
    artifacts:
        name: "libdraco.macos.%CI_PIPELINE_ID%.%CI_JOB_ID%"
        expire_in: 1 week
        paths:
            - output/lib/*
    tags:
        - macos
        - gcc
        - cmake
        - make

package_ue4.10:
    stage: package
    script:
        - 'xcopy README.md libdraco_ue4\README.md* /r /y'
        - 'xcopy LICENSE.md libdraco_ue4\LICENSE.md* /r /y'
        - 'xcopy libdraco_ue4.10.Build.cs libdraco_ue4\libdraco_ue4.Build.cs* /r /y'
        - 'xcopy external\draco\src\draco\core\*.h libdraco_ue4\libdraco-1.2.5\include\draco\core\ /s/r/y'
        - 'xcopy external\draco\src\draco\metadata\*.h libdraco_ue4\libdraco-1.2.5\include\draco\metadata\ /s /r /y'
        - 'xcopy external\draco\src\draco\mesh\*.h libdraco_ue4\libdraco-1.2.5\include\draco\mesh\ /s /r /y'
        - 'xcopy external\draco\src\draco\point_cloud\*.h libdraco_ue4\libdraco-1.2.5\include\draco\point_cloud\ /s /r /y'
        - 'xcopy external\draco\src\draco\attributes\*.h libdraco_ue4\libdraco-1.2.5\include\draco\attributes\ /s /r /y'
        - 'xcopy external\draco\src\draco\compression\*.h libdraco_ue4\libdraco-1.2.5\include\draco\compression\ /s /r /y'
        - 'xcopy external\draco\src\draco\io\*.h libdraco_ue4\libdraco-1.2.5\include\draco\io\ /s /r /y'
        - 'xcopy output\lib\*.* libdraco_ue4\libdraco-1.2.5\lib\ /s /r /y'
    dependencies:
        - compile_draco.windows
        - compile_draco.linux
        - compile_draco.macos
    artifacts:
        name: "libdrack_ue4.10.%CI_PIPELINE_ID%.%CI_JOB_ID%"
        expire_in: 1 week
        paths:
            - libdraco_ue4/*
    tags:
        - win32
        - win64

libdraco_ue4.10:
    stage: deploy
    script:
        - 'mkdir output'
        - 'mv ./libdraco_ue4 ./output'
        - 'butler login'
        - 'butler push ./output c4gio/libdraco-ue4:ue4.10'
        - 'butler logout'
    artifacts:
        name: "$CI_JOB_NAME.$CI_PIPELINE_ID"
        expire_in: 1 week
        paths:
            - $CI_JOB_NAME/*
    when: manual
    dependencies:
        - package_ue4.10
    tags:
        - linux
        - python
        - itchio
        - butler

package_ue4.16:
    stage: package
    script:
        - 'xcopy README.md libdraco_ue4\README.md* /r /y'
        - 'xcopy LICENSE.md libdraco_ue4\LICENSE.md* /r /y'
        - 'xcopy libdraco_ue4.16.Build.cs libdraco_ue4\libdraco_ue4.Build.cs* /r /y'
        - 'xcopy external\draco\src\draco\core\*.h libdraco_ue4\libdraco-1.2.5\include\draco\core\ /s/r/y'
        - 'xcopy external\draco\src\draco\metadata\*.h libdraco_ue4\libdraco-1.2.5\include\draco\metadata\ /s /r /y'
        - 'xcopy external\draco\src\draco\mesh\*.h libdraco_ue4\libdraco-1.2.5\include\draco\mesh\ /s /r /y'
        - 'xcopy external\draco\src\draco\point_cloud\*.h libdraco_ue4\libdraco-1.2.5\include\draco\point_cloud\ /s /r /y'
        - 'xcopy external\draco\src\draco\attributes\*.h libdraco_ue4\libdraco-1.2.5\include\draco\attributes\ /s /r /y'
        - 'xcopy external\draco\src\draco\compression\*.h libdraco_ue4\libdraco-1.2.5\include\draco\compression\ /s /r /y'
        - 'xcopy external\draco\src\draco\io\*.h libdraco_ue4\libdraco-1.2.5\include\draco\io\ /s /r /y'
        - 'xcopy output\lib\*.* libdraco_ue4\libdraco-1.2.5\lib\ /s /r /y'
    dependencies:
        - compile_draco.windows
        - compile_draco.linux
        - compile_draco.macos
    artifacts:
        name: "libdrack_ue4.16.%CI_PIPELINE_ID%.%CI_JOB_ID%"
        expire_in: 1 week
        paths:
            - libdraco_ue4/*
    tags:
        - win32
        - win64

libdraco_ue4.16:
    stage: deploy
    script:
        - 'mkdir output'
        - 'mv ./libdraco_ue4 ./output'
        - 'butler login'
        - 'butler push ./output c4gio/libdraco-ue4:ue4.16'
        - 'butler logout'
    artifacts:
        name: "$CI_JOB_NAME.$CI_PIPELINE_ID"
        expire_in: 1 week
        paths:
            - $CI_JOB_NAME/*
    when: manual
    dependencies:
        - package_ue4.16
    tags:
        - linux
        - python
        - itchio
        - butler
